import { Handle, Setter } from "./Handle";

export class Widget extends Handle {
  public toHandle(): HWidget | null {
    return this.handle as HWidget;
  }

  ///
  /// Autogenerated
  ///

  ///
  /// Functions
  ///

  public setTexture(textureName: string, textureIndex: number): this {
    SetWidgetTexture(this.toHandle(), textureName, textureIndex);
    return this;
  }

  public getVertexColour(): number {
    return GetWidgetVertexColour(this.toHandle());
  }

  public addIndicator(red: number, green: number, blue: number, alpha: number): this {
    AddIndicator(this.toHandle(), red, green, blue, alpha);
    return this;
  }

  public setPosition(x: number, y: number): this {
    SetWidgetPosition(this.toHandle(), x, y);
    return this;
  }

  public setSpaceRotation(yaw: number, pitch: number, roll: number, eulerOrder: number): this {
    SetWidgetSpaceRotation(this.toHandle(), yaw, pitch, roll, eulerOrder);
    return this;
  }

  public setAnimationWithRarity(animation: string, rarity: HRarityControl): this {
    SetWidgetAnimationWithRarity(this.toHandle(), animation, rarity);
    return this;
  }

  public setReplaceableTexture(textureName: string, textureIndex: number): this {
    SetWidgetReplaceableTexture(this.toHandle(), textureName, textureIndex);
    return this;
  }

  public setModelEx(modelFile: string, playerId: number): this {
    SetWidgetModelEx(this.toHandle(), modelFile, playerId);
    return this;
  }

  public setModel(modelFile: string): this {
    SetWidgetModel(this.toHandle(), modelFile);
    return this;
  }

  public setAnimationWithRarityByIndex(animIndex: number, rarity: HRarityControl): this {
    SetWidgetAnimationWithRarityByIndex(this.toHandle(), animIndex, rarity);
    return this;
  }

  public setMaterialTexture(textureName: string, materialId: number, textureIndex: number): this {
    SetWidgetMaterialTexture(this.toHandle(), textureName, materialId, textureIndex);
    return this;
  }

  public queueAnimationByIndex(animIndex: number): this {
    QueueWidgetAnimationByIndex(this.toHandle(), animIndex);
    return this;
  }

  public getFacing(): number {
    return GetWidgetFacing(this.toHandle());
  }

  public queueAnimation(animation: string): this {
    QueueWidgetAnimation(this.toHandle(), animation);
    return this;
  }

  public setFacing(facing: number, isInstant: boolean): this {
    SetWidgetFacing(this.toHandle(), facing, isInstant);
    return this;
  }

  public setVertexColour(red: number, green: number, blue: number, alpha: number): this {
    SetWidgetVertexColour(this.toHandle(), red, green, blue, alpha);
    return this;
  }

  public setAnimationByIndex(animIndex: number): this {
    SetWidgetAnimationByIndex(this.toHandle(), animIndex);
    return this;
  }

  public setOrientation(yaw: number, pitch: number, roll: number): this {
    SetWidgetOrientation(this.toHandle(), yaw, pitch, roll);
    return this;
  }

  public setAnimation(animation: string): this {
    SetWidgetAnimation(this.toHandle(), animation);
    return this;
  }

  ///
  /// Props
  ///

  public timeScale(): number;
  public timeScale(value: Setter<number, this>): this;
  public timeScale(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetTimeScale(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetTimeScale(this.toHandle());
    }

    SetWidgetTimeScale(this.toHandle(), value);
    return this;
  }

  public invulnerable(): boolean;
  public invulnerable(value: Setter<boolean, this>): this;
  public invulnerable(value?: Setter<boolean, this>): boolean | this {
    if (typeof value === "function") {
      value = value(IsWidgetInvulnerable(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return IsWidgetInvulnerable(this.toHandle());
    }

    SetWidgetInvulnerable(this.toHandle(), value);
    return this;
  }

  public pitch(): number;
  public pitch(value: Setter<number, this>): this;
  public pitch(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetPitch(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetPitch(this.toHandle());
    }

    SetWidgetPitch(this.toHandle(), value);
    return this;
  }

  public visible(): boolean;
  public visible(value: Setter<boolean, this>): this;
  public visible(value?: Setter<boolean, this>): boolean | this {
    if (typeof value === "function") {
      value = value(IsWidgetVisible(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return IsWidgetVisible(this.toHandle());
    }

    SetWidgetVisible(this.toHandle(), value);
    return this;
  }

  public positionLocation(): HLocation;
  public positionLocation(value: Setter<HLocation, this>): this;
  public positionLocation(value?: Setter<HLocation, this>): HLocation | this {
    if (typeof value === "function") {
      value = value(GetWidgetPositionLocation(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetPositionLocation(this.toHandle());
    }

    SetWidgetPositionLocation(this.toHandle(), value);
    return this;
  }

  public roll(): number;
  public roll(value: Setter<number, this>): this;
  public roll(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetRoll(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetRoll(this.toHandle());
    }

    SetWidgetRoll(this.toHandle(), value);
    return this;
  }

  public life(): number;
  public life(value: Setter<number, this>): this;
  public life(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetLife(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetLife(this.toHandle());
    }

    SetWidgetLife(this.toHandle(), value);
    return this;
  }

  public x(): number;
  public x(value: Setter<number, this>): this;
  public x(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetX(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetX(this.toHandle());
    }

    SetWidgetX(this.toHandle(), value);
    return this;
  }

  public scale(): number;
  public scale(value: Setter<number, this>): this;
  public scale(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetScale(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetScale(this.toHandle());
    }

    SetWidgetScale(this.toHandle(), value);
    return this;
  }

  public y(): number;
  public y(value: Setter<number, this>): this;
  public y(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetY(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetY(this.toHandle());
    }

    SetWidgetY(this.toHandle(), value);
    return this;
  }

  public yaw(): number;
  public yaw(value: Setter<number, this>): this;
  public yaw(value?: Setter<number, this>): number | this {
    if (typeof value === "function") {
      value = value(GetWidgetYaw(this.toHandle()), this);
    }

    if (typeof value === "undefined") {
      return GetWidgetYaw(this.toHandle());
    }

    SetWidgetYaw(this.toHandle(), value);
    return this;
  }
}
